[mcp_servers.reverse_lab_tools]
command = "uv"
args = ["run", "--project", "C:/Users/Administrator/AppData/Local/Claude-3p/open-reverselab-main/open-tgtylab/tools/skills/mcp/ReverseLabToolsMCP", "python", "C:/Users/Administrator/AppData/Local/Claude-3p/open-reverselab-main/open-tgtylab/tools/skills/mcp/ReverseLabToolsMCP/reverse_lab_tools_mcp.py"]
startup_timeout_sec = 30
